version: '3.8'

services:
  thesis-simulation:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py"]
